name: Service Management CI

# Run this workflow on push or pull request events for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # Job to set up Python environment and run tests
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements_dev.txt

    - name: Run unit tests
      run: |
        pytest --cov=src tests/unit

    - name: Run integration tests
      run: |
        pytest tests/integration

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: tests/results

  # Job to build and push Docker images
  build_and_push_docker:
    runs-on: ubuntu-latest
    needs: test  # This job depends on the 'test' job

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker images
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/file_service:latest -f Dockerfile .
        docker push ${{ secrets.DOCKER_USERNAME }}/file_service:latest
        docker build -t ${{ secrets.DOCKER_USERNAME }}/prediction_service:latest -f Dockerfile .
        docker push ${{ secrets.DOCKER_USERNAME }}/prediction_service:latest
